certificate/certificate/urls.py
from django.conf import settings
from django.conf.urls.static import  static
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth.views import TemplateView,PasswordResetView,LoginView,LogoutView
from certificate_app.views import signup,useractivation,personal_detail,project_detail,test
from certificate_app.reportsubmissionview import reportview,reportupdate
from certificate_app.certificateview import adminpage,intern_detail,create_certificate,change_status

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('accounts/', include('registration.backends.default.urls')),
    path('',TemplateView.as_view(template_name='certificate_app/index.html'),name='home'),
    path('signup',signup,name='signup'),
    path('activate/<uibd64>/<token>',useractivation,name='activate'),
    path('login',LoginView.as_view(template_name='certificate_app/usercreation.html'),name='login'),
    path('logout',LogoutView.as_view(),name='logout'),

    # report submissiion view
    # path('report',reportsumission,name='report'),
    path('reportview',reportview,name='reportview'),
    path('report/update',reportupdate,name='reportupdate'),

    # certificate view urls
    path('adminpage',adminpage,name='adminpage'),
    path('interdetail/<pk>',intern_detail,name='interndetail'),
    path('createcertificate/<pk>',create_certificate,name='create_certificate'),
    path('interndetail/<pk>',change_status,name='change_status'),


    #personal detail
    path('personalform',personal_detail,name="personal_form"),
    path('projectform',project_detail,name="project_form"),
    path('test',test,name="test"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

certificate/certificate_app/models.py
import uuid
import string
import random
from django.db import models
from django.conf import settings

User = settings.AUTH_USER_MODEL

# PROJECT_WORKED_CHOICE = [
#     ('irsc','IRSC'),
#     ('intellify','Intellify'),
#     ('isafe','iSAFE Assisst'),
#     ('solve','Solve(Multiple Projects)'),
# ]
# PROFILE_CHOICE = [
#     ('FR', 'Freshman'),
#     ('SO', 'Sophomore'),
#     ('JR', 'Junior'),
#     ('SR', 'Senior'),
#     ('GR', 'Graduate'),
# ]
# TYPE_OF_INTERNSHIP = [
#     ('wfh', 'work from home'),
#     ('wfo', 'wrok from office')
# ]

# STATUS = [
#     ('V', 'Volunteer'),
#     ('I', 'Intern')
# ]
# TENURE_CHOICE = [(f'{i} Month', f'{i} month') for i in range(1,13)]
class ProjectWorkedChoice(models.Model):
    project_worked = models.CharField(max_length=225)

    def __str__(self):
        return "{}".format(self.project_worked)

class ProfileChoice(models.Model):
    profile = models.CharField(max_length=225)

    def __str__(self):
        return "{}".format(self.profile)

class StatusChoice(models.Model):
    status = models.CharField(max_length=225)

    def __str__(self):
        return "{}".format(self.status)

class TypeOfInternChoice(models.Model):
    type_of_intern = models.CharField(max_length=225)

    def __str__(self):
        return "{}".format(self.type_of_intern)

class TenureChoice(models.Model):
    tenure = models.CharField(max_length=30)

    def __str__(self):
        return "{}".format(self.tenure)

class Registration(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    registration_number = models.CharField(max_length=225,editable=False,unique=True)

    def save(self, *args, **kwargs):
        self.registration_number = "".join(random.choices(string.digits,k=8))
        super(Registration, self).save(*args, **kwargs)

    def __str__(self):
        return "{} - {}".format(self.user.get_full_name(),self.registration_number)

class Certificate(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    certificate_number = models.UUIDField(default=uuid.uuid4,editable=False,unique=True)
    certificate_pdf = models.FileField(upload_to='certificates/pdf',default='default.pdf')
    certificate_png = models.FileField(upload_to='certificates/png',default='default.png')

    def __str__(self):
        return "{} - {}".format(self.user.get_full_name(),self.certificate_number)


REPORT_STATUS = [
    ('A', 'Approved'),
    ('P', 'Pending'),
    ('R', 'Rejected')
]

class PersonalDetail(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    ph_contact_no = models.CharField(max_length=15)
    whatsapp_no = models.CharField(max_length=15)
    project = models.ForeignKey(ProjectWorkedChoice,on_delete=models.CASCADE)
    profile = models.ForeignKey(ProfileChoice,on_delete=models.CASCADE)
    type_of_internship = models.ForeignKey(TypeOfInternChoice,on_delete=models.CASCADE)
    joining_date = models.DateField(auto_now_add=True)
    pan_number = models.CharField(max_length=20)
    aadhaar = models.CharField(max_length=20)
    emergency_contact_no = models.CharField(max_length=15)
    bank_account_no = models.CharField(max_length=20)
    ifsc_code = models.CharField(max_length=15)
    dob = models.DateField()
    permanent_address = models.TextField()
    current_address = models.TextField()
    biometric_id_number = models.CharField(max_length=225)
    internship_tenure = models.ForeignKey(TenureChoice,on_delete=models.CASCADE)
    resume = models.FileField(upload_to='resume')

    def __str__(self):
        return "{}".format(self.user.get_full_name())

class Project(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    profile = models.ForeignKey(ProfileChoice,on_delete=models.CASCADE)
    project_worked_on = models.ForeignKey(ProjectWorkedChoice,on_delete=models.CASCADE)
    status = models.ForeignKey(StatusChoice,on_delete=models.CASCADE)
    tenure = models.ForeignKey(TenureChoice,on_delete=models.CASCADE)
    joining_date = models.DateField()
    end_date = models.DateField()
    upload_traker_link = models.URLField()
    mentor_or_leader = models.TextField()

    def __str__(self):
        return "{} - {}".format(self.user.first_name,self.project_worked_on)


class Report(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    project_name = models.CharField(max_length=500)
    upload_report = models.FileField(upload_to='reports')
    status = models.CharField(choices=REPORT_STATUS, max_length=2,default='P')

    def __str__(self):
        return "{} - Project: {}, status: {}".format(self.user.first_name,self.project_name,self.status)

certificate/certificate_app/forms.py
from django.contrib.auth.forms import UserCreationForm as ucf
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.db import models
from django.core.exceptions import ValidationError
from .models import PersonalDetail,Project

class UserCreationForm(ucf):
    class Meta():
        model = User
        fields = ['email','username','first_name','last_name',
            'password1','password2']

class SignupForm(ModelForm):
    class Meta():
        model = User
        fields = ['email','username']

    def clean(self):
        cleaned_data = super().clean()
        email = cleaned_data.get("email")
        if User.objects.filter(email=email).exists():
            msg = 'Email already exists.'
            self.add_error('email', msg)

class PersonalDetailForm(ModelForm):
    class Meta():
        model = PersonalDetail
        fields = "__all__"

class ProjectForm(ModelForm):
    class Meta():
        model = Project
        fields = "__all__"

certificate/certificate_app/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,JsonResponse
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes,force_text
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_decode,urlsafe_base64_encode
from django.core.mail import EmailMessage
from django.contrib.auth import login,authenticate

from .models import Registration
from .forms import UserCreationForm,SignupForm,User,PersonalDetailForm,ProjectForm
from .token import emailactivationtokengenarator

# Create your views here.
def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()

            uid = urlsafe_base64_encode(force_bytes(user.id))
            token = emailactivationtokengenarator.make_token(user)
            current_site = get_current_site(request)
            mail_subject = 'Activate Your account.'

            message = render_to_string('certificate_app/activationmail.html',{
                'user':user,
                'domain': current_site,
                'uid':str(uid),
                'token':str(token)
            })

            to_email = form.cleaned_data.get('email')
            email = EmailMessage(mail_subject,message,to=[to_email])
            email.send()

            return HttpResponse('An email has been sent to you with instructions further')
        return render(request,'certificate_app/signup.html',{'form':form})
    form = SignupForm()
    return render(request,'certificate_app/signup.html',{'form':form})

def useractivation(request,uibd64,token):
    if request.method == 'GET':
        try:
            uid = force_text(urlsafe_base64_decode(uibd64))
            user = User.objects.get(id=uid)
        except(TypeError,ValueError,OverflowError,
    User.DoesNotExist):
            user = None

        if user is not None and \
            emailactivationtokengenarator.check_token(user,token):
            # user.is_active = True
            form = UserCreationForm(instance = user)
            return render(request,'certificate_app/usercreation.html',{'form':form})
        return HttpResponse('invalid token')
    elif request.method == 'POST':
        uid = force_text(urlsafe_base64_decode(uibd64))
        user = User.objects.get(id=uid)
        user.is_active = True
        form = UserCreationForm(request.POST,instance = user)
        if form.is_valid():
            form.save()
            return redirect('home')
        return render(request,'certificate_app/usercreation.html',{'form':form})


def personal_detail(request):
    form = PersonalDetailForm()
    if request.method == 'POST':
        form = PersonalDetailForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            return redirect('personal_form')
    return render(request,'certificate_app/personal_form.html',{'form':form})

def project_detail(request):
    form = ProjectForm()
    if request.method == 'POST':
        form = ProjectForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            return redirect('personal_form')
    return render(request,'certificate_app/project_form.html',{'form':form})


def test(request):
    if request.is_ajax():
        data = render_to_string('certificate_app/test.html')
        return JsonResponse(data, safe=False)
    # return render(request,'certificate_app/reportview.html')
    return JsonResponse({'data':None})

certificate/certificate_app/templates/certificate_app/activationmail.html
{% autoescape off %}  
Hi {{ user.username }},  
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'activate' uid token %}  
If you think, it's not you, then just ignore this email.  
{% endautoescape %}

certificate/certificate_app/templates/certificate_app/adminpage.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="navbar navbar-expand-lg navbar-light bg-light mb-2">
        <div class="container-fluid">
            <h3>Internship Details and Certificate</h3>
            <!-- <div class="collapse navbar-collapse"> -->
            <!-- <ul class="navbar-nav mr-auto mb-2 mb-lg-0"></ul> -->
            <div class="ml-auto d-flex">
                <ul class="navbar-nav">
                    <li class="nav-item px-1"><strong class="nav-link">Hi {{request.user.get_full_name}}</strong></li>
                    <li class="nav-item px-1"><a class="nav-link" href="{% url 'logout' %}">signout</a></li>
                </ul>
            </div>
            <!-- </div> -->
        </div>
    </div>
    <div class="bg-light p-5 rounded">
        <form class="row row-cols-md-auto g-3 align-items-center">
            <div class="col-12">
                <select class="form-select" aria-label="Default select example" id="select" onchange="selectType()">
                    <option selected value='1'>search Intern by</option>
                    <option value="first_name">First Name</option>
                    <option value="last_name">Last Name</option>
                    <option value="reg_number">Registration Number</option>
                    <option value="days_from_now">Internship ending within days from now</option>
                </select>
            </div>
            <div class="col-12">
                <input disabled class="form-control" type="text" name="" id="searchfield" min="0">
            </div>
            <div class="col-12">
                <button class='btn btn-sm btn-primary' type="submit">search</button>
            </div>
        </form>
    </div>
</div>
<div class="table-responsive bg-light mt-3 px-1">
    <table class="table text-center">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Details</th>
                <th scope="col">Reg. No.</th>
                <th scope="col">First Name</th>
                <th scope="col">Last Name</th>
                <th scope="col">Mentor</th>
                <th scope="col">Start Date</th>
                <th scope="col">End Date</th>
                <th scope="col">Report</th>
                <th scope="col">Marked status</th>
                <th scope="col">Certificate Generated</th>
                <th scope="col">Certificate Serial No.</th>
            </tr>
        </thead>
        <tbody>
            {% for u in user %}
            <tr>
                <th scope="row">{{forloop.counter}}.</th>
                <td><a style="cursor: pointer;" class="text-decoration-none" data-toggle="modal"
                        data-target="#exampleModal{{u.id}}">view</a></td>

                <!-- Modal -->
                <div class="modal fade" id="exampleModal{{u.id}}" tabindex="-1" aria-labelledby="exampleModalLabel"
                    aria-hidden="true">
                    <div class="modal-dialog modal-dialog-scrollable" style="max-width: 90%;">
                        <div class="modal-content mb-4">
                            <div class="modal-header bg-light p-3">
                                <!-- <h5 class="modal-title" id="exampleModalLabel">Modal title</h5> -->
                                <h5 class="modal-title">Intern details</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body{{u.id}}">
                                <div>
                                    {% include 'certificate_app/interndetail.html' with user=u project=u.project report=u.report details=u.personaldetail %}
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div>
                </div>

                {% comment %}
                <script>
                    var myModal = document.getElementById('exampleModal{{u.id}}')

                    myModal.addEventListener('shown.bs.modal', function () {
                        $.ajax({
                            url: "{% url 'interndetail' u.id %}",
                            success: (data) => {
                                $('.modal-body{{u.id}}').append(data)
                            }
                        });
                    })
                </script> {% endcomment %}

                <td>{{u.registration.registration_number}}</td>
                <td>{{u.first_name}}</td>
                <td>{{u.last_name}}</td>
                <td>{{u.project.mentor_or_leader}}</td>
                <td>{{u.project.joining_date}}</td>
                <td>{{u.project.end_date}}</td>
                {% if u.report %}
                <td>Submitted</td>
                <td>{{u.report.get_status_display}}</td>
                {% else %}
                <td>Not Submitted</td>
                <td>-</td>
                {% endif %}

                {% if u.certificate %}
                <td>yes</td>
                <td><a class="text-decoration-none"
                        href="{{u.certificate.certificate_pdf.url}}">{{u.certificate.certificate_number}}</a></td>
                {% else %}
                <td>No</td>
                <td>-</td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% if not user %}
    <h2>No search results.</h2>
    {% endif %}
</div>
<script>
    function selectType() {
        var option = document.getElementById('select')
        var searchfield = document.getElementById('searchfield')
        searchfield.name = option.value
        if (option.value == 'days_from_now') {
            searchfield.type = 'number'
            searchfield.placeholder = 'days'
        }
        else {
            searchfield.type = 'text'
            searchfield.placeholder = option.options[option.selectedIndex].text
        }
        if (option.value == '1') {
            searchfield.disabled = true
        }
        else searchfield.disabled = false
    }
    function changestatus(self,url,id,ckturl){
        self = $(self)
        self.children('span').show()
        $.ajax({
            url:url,
            success:(data) => {
                self.children('span').hide()
                // console.log(data,self.text())
                if(self.text().trim()=='Approve'){
                    $(`#status${id}`).text('Approved')
                    $('.statuschange').hide('normal')
                    var btn = `<button class="btn btn-success mx-5"onclick="generatecertificate(this,'${ckturl}')"><span class="spinner-border spinner-border-sm mr-1" role="status" aria-hidden="true" style="display: none;"></span>Generate Certificate</button>`
                    $('.statuschange').parent().append(btn).hide().show('normal')
                }else{
                    $(`#status${id}`).text('Rejected')
                    $('.statuschange').hide('normal')
                }
            },
            error:(data) => {
                self.children('span').hide()
                console.log('something went wrong',data)
            }
        })
    }

    function generatecertificate(self,url){
        self = $(self)
        self.children('span').show()
        $.ajax({
            url:url,
            success:(data) => {
                self.children('span').hide()
                self.hide('normal')
                // console.log(data)
                pdfurl = data['pdfurl']
                pngurl = data['pngurl']
                ckt = $(`<div class="row px-sm-5 my-2"><div class="col-4"><strong>Certificate Generated</strong></div><div class="col-8 align-self-center text-break"><a href=${pdfurl} target="=_blank">PDF</a> <a href=${pngurl} download target="=_blank"> PNG</a></div></div>`).hide()
                ckt.insertAfter('#statusdiv').show('normal')
                // $('#report').append(ckt.show('normal'))
            },
            error:(data) => {
                self.children('span').hide()
                console.log(data)
            }
        })
    }
</script>
{% endblock content %}

certificate/certificate_app/templates/certificate_app/certificate.html
{% extends 'base.html' %}
{% block content %}
<h2>Welcome certificate generate page</h2>
<div>

</div>
{% endblock content %}

certificate/certificate_app/templates/certificate_app/index.html
{% extends 'base.html' %}
{% block content %}
{% if user.is_authenticated %}
<h1>
    Welcome {{user.username}} <a href="{% url 'logout' %}">logout</a> here.
</h1>
{% else %}
<h1>
    Goto <a href="login">login</a> page or <a href="signup">register</a> page.
</h1>
{% endif %}
{% endblock content %}

certificate/certificate_app/templates/certificate_app/login.html
{% extends 'base.html' %}
{% block content %}
<form method="post">
{% csrf_token %}
{{form}}
<button type="submit">Login</button>
</form>
{% endblock content %}

certificate/certificate_app/templates/certificate_app/personal_form.html
{% extends 'base.html' %}
{% block content %}
<form action="" method="post" enctype="multipart/form-data">
{% csrf_token %}
{{form.as_p}}
<button type="submit">Save</button>
</form>
{% endblock content %}

certificate/certificate_app/templates/certificate_app/project_form.html
{% extends 'base.html' %}
{% block content %}
<form method="post" enctype="multipart/form-data">
{% csrf_token %}
{{form}}
<button type="submit">Save</button>
</form>
{% endblock content %}

certificate/certificate_app/templates/certificate_app/report.html
{% extends 'base.html' %}
{% block content %}
<nav class="bg-light">
    <ul class="nav nav-tabs px-5 pt-4">
        <li class="nav-item">
            <a class="nav-link" href="#">Personal Details</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Projects Details</a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" href="#">Report Details</a>
        </li>
    </ul>
</nav>
<div class="container my-3">
    <div class="bg-light p-md-4 p-2">
        <div class="mx-auto" style="max-width: 500px;">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="mb-3 row">
                    {{ form.project_name.errors }}
                    <label for="{{ form.project_name.id_for_label }}" class="col-sm-4 col-form-label">Project Name :</label>
                    <div class="col-sm-8">
                        <input class="form-control" type="text" name="project_name" maxlength="100" required="" id="id_project_name" value="{{request.user.report.project_name}}">
                    </div>
                </div>
                <div class="mb-3 row">
                    <label for="{{ form.project_name.id_for_label }}" class="col-sm-4 col-form-label">Currently Upload Report :</label>
                    <a class="col-sm-8" href={{request.user.report.upload_report.url}}>{{request.user.report.upload_report}}</a>
                </div>
                <div class="mb-3 row">
                    {{ form.upload_report.errors }}
                    <label for="{{ form.project_name.id_for_label }}" class="col-sm-4 col-form-label">Upload New Report :</label>
                    <input class="col-sm-8" type="file" name="upload_report" required="" id="id_upload_report">
                </div>
                <button class="btn btn-sm btn-primary" type="submit">Update</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

certificate/certificate_app/templates/certificate_app/reportview.html
{% extends 'base.html' %}
{% block content %}
<nav class="bg-light">
    <ul class="nav nav-tabs px-5 pt-4">
        <li class="nav-item">
            <a class="nav-link" href="#">Personal Details</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Projects Details</a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" href="#">Report Details</a>
        </li>
    </ul>
</nav>
<div class="container my-3">
    {% if request.user.report %}
    <div class="bg-light p-md-4 p-2">
        <div class="row px-sm-5 my-2">
            <div class="col-4"><strong>Report Name</strong></div>
            <div class="col-8 align-self-center">
                {{request.user.report.project_name}}
            </div>
        </div>
        <div class="row px-sm-5 my-2">
            <div class="col-4"><strong>Report Url</strong></div>
            <div class="col-8 align-self-center">
                <a class="text-break" href="{{request.user.report.upload_report.url}}">{{request.user.report.upload_report.url}}</a>
            </div>
        </div>
        <div class="row px-sm-5 my-2">
            <div class="col-4"><strong>Status</strong></div>
            <div class="col-8 align-self-center">
                {{request.user.report.get_status_display}}
            </div>
        </div>
        {% if request.user.report.status == 'R' %}
        <a class="btn btn-sm btn-dark ml-sm-5 mt-sm-4 mt-2" href="{% url 'reportupdate' %}">Update report</a>
        {% elif request.user.report.status == 'A' and request.user.certificate %}
        <div class="row px-sm-5 my-2">
            <div class="col-4"><strong>Certificate Generated</strong></div>
            <div class="col-8 align-self-center">
                <a href="#">Download Certificate</a>
            </div>
        </div>
        {% endif %}
    </div>
    {% else %}
    <div class="mx-auto" style="max-width: 550px;">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-3 row">
                {{ form.project_name.errors }}
                <label for="{{ form.project_name.id_for_label }}" class="col-sm-3 col-form-label">Project Name :</label>
                <div class="col-sm-9">
                    <input class="form-control" type="text" name="project_name" maxlength="100" required=""
                        id="id_project_name">
                </div>
            </div>
            <div class="mb-3 row">
                {{ form.upload_report.errors }}
                <label for="{{ form.project_name.id_for_label }}" class="col-sm-3 col-form-label">Upload Report
                    :</label>
                <input class="col-sm-9" type="file" name="upload_report" required="" id="id_upload_report">
            </div>
            <button class="btn btn-sm btn-primary" type="submit">submit</button>
        </form>
    </div>
    {% endif %}
</div>
{% endblock content %}

certificate/certificate_app/templates/certificate_app/signup.html
{% extends 'base.html' %}
{% block content %}
<form method="post">
{% csrf_token %}
{{form.as_p}}
<button type="submit">sigup</button>
</form>
{% endblock content %}

certificate/certificate_app/templates/certificate_app/test.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<nav class="bg-light">
    <ul class="nav nav-tabs px-5 pt-4">
        <li class="nav-item">
            <a class="nav-link" href="#">Personal Details</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Projects Details</a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" href="{% url 'adminpage' %}">Report Details</a>
        </li>
    </ul>
</nav>
<div class="container my-3">
    {% if request.user.report %}
    <div class="bg-light p-md-4 p-2">
        <div class="row px-sm-5 my-2">
            <div class="col-4"><strong>Report Name</strong></div>
            <div class="col-8 align-self-center">
                {{request.user.report.project_name}}
            </div>
        </div>
        <div class="row px-sm-5 my-2">
            <div class="col-4"><strong>Report Url</strong></div>
            <div class="col-8 align-self-center">
                <a class="text-break" href="{{request.user.report.upload_report.url}}">{{request.user.report.upload_report.url}}</a>
            </div>
        </div>
        <div class="row px-sm-5 my-2">
            <div class="col-4"><strong>Status</strong></div>
            <div class="col-8 align-self-center">
                {{request.user.report.get_status_display}}
            </div>
        </div>
        {% if request.user.report.status == 'R' %}
        <a class="btn btn-sm btn-dark ml-sm-5 mt-sm-4 mt-2" href="{% url 'reportupdate' %}">Update report</a>
        {% elif request.user.report.status == 'A' and request.user.certificate %}
        <div class="row px-sm-5 my-2">
            <div class="col-4"><strong>Certificate Generated</strong></div>
            <div class="col-8 align-self-center">
                <a href="{{request.user.certificate.certificate_pdf.url}}">Download Certificate</a>
            </div>
        </div>
        {% endif %}
    </div>
    {% else %}
    <div class="mx-auto" style="max-width: 550px;">
    </div>
    {% endif %}
</div>
{% endblock content %}

certificate/certificate_app/templates/certificate_app/usercreation.html
{% extends 'base.html' %}
{% block content %}
<form method="post">
{% csrf_token %}
{{form}}
<button type="submit">create user</button>
</form>
{% endblock content %}